[registration] Fix typo in gicp and use constructor with size
PointCloudLibrary/pcl pull request #5161
Opened 2022-02-08 01:47 UTC by keineahnung2345

1. nn_indecies->nn_indices
2. use constructor with size

2022-02-08 13:05 UTC, mvieth commented
Why did you decide to switch from reserve to constructor with size? Note that reserve only allocates memory (capacity), but the constructor with size also initializes the memory (actual size). If you don't have a reason why the constructor variant is better, I would prefer to keep the original way with reserve

2022-02-08 13:20 UTC, kunaltyagi requested changes

2022-02-08 13:20 UTC, kunaltyagi commented on registration/include/pcl/registration/impl/gicp.hpp
> +  pcl::Indices nn_indices(k_correspondences_);
Please revert changes from L65-L68 and keep changes that are related to the title

2022-02-09 01:32 UTC, keineahnung2345 commented
@mvieth By searching `nn_indices` in pcl code base, I found that they are mostly built using constructor with size. But anyway I've reverted this change.

2022-02-09 09:26 UTC, mvieth approved these changes

2022-02-10 07:45 UTC, kunaltyagi approved these changes

2022-02-10 08:43 UTC, merged